homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 273
  unit_system: imperial
  time_zone: America/Detroit
  customize: !include customize.yaml

group: !include groups.yaml
automation: !include_dir_merge_list automations
input_boolean: !include input_boolean.yaml
input_select: !include input_select.yaml
switch: !include switches.yaml
script: !include_dir_merge_named scripts
sensor: !include_dir_merge_list sensors
scene: !include_dir_merge_list scenes
shell_command: !include shell_command.yaml

discovery:

history:

logbook:
#  exclude:
#    domains:
#      - group

updater:
  include_used_components: true

logger:
  default: warning
  logs:
    homeassistant.helpers.entity: fatal
    homeassistant.components.vacuum.xiaomi_miio: fatal
    mirobo.device: fatal
    requests.packages.urllib3.connectionpool: fatal

wemo:
#  static:
#    - 192.168.0.127

recorder:
  purge_interval: 2
  purge_keep_days: 1

sun:

config:

mqtt:
  broker: 192.168.0.107

emulated_hue:
  host_ip: 192.168.0.107
  listen_port: 80
  expose_by_default: false

http:
  api_password: !secret http_password
  ip_ban_enabled: True
  login_attempts_threshold: 1
  base_url: !secret base_url

device_tracker:
  - platform: bluetooth_tracker
    interval_seconds: 15
    consider_home: 300
    track_new_devices: False
  - platform: nmap_tracker
    hosts:
      - 192.168.0.100 # Derek's Hue Hub
      - 192.168.0.118 # Nolan's Hue Hub
      - 192.168.0.130 # Amazon Firestick
      - 192.168.0.105 # Hyperion
      - 192.168.0.102 # Xiaomi Vacuum
      - 192.168.0.104 # Broadlink RM Pro
      - 192.168.0.108 # Iphone
      - 192.168.0.129 # Kalee's Laptop
      - 192.168.0.123 # Google Home (Still needs static IP) F4-F5-D8-DA-4A-22

notify:
# NOLAN
  - name: pushbullet
    platform: pushbullet
    api_key: !secret pushbullet_api_key
  - name: nolan
    platform: group
    services:
      - service: pushbullet
        data:
          target: !secret nolans_pushbullet_email
# DEREK
  - name: derek
    platform: telegram
    chat_id: !secret dereks_telegram_id
# KALEE
  - name: kalee
    platform: telegram
    chat_id: !secret kalees_telegram_id
# DEREK AND KALEE
  - name: derek and kalee
    platform: group
    services:
      - service: derek
      - service: kalee
# DEREK AND NOLAN
  - name: derek and nolan
    platform: group
    services:
      - service: derek
      - service: nolan
# KALEE AND NOLAN
  - name: kalee and nolan
    platform: group
    services:
      - service: nolan
      - service: kalee
# LIVING ROOM FIRETV
  - name: living room tv
    platform: nfandroidtv
    host: 192.168.0.130
# HOUSEHOLD
  - name: household
    platform: group
    services:
      - service: derek
      - service: kalee
      - service: nolan
# EVERYTHING
  - name: all
    platform: group
    services:
      - service: derek
      - service: kalee
      - service: nolan
      - service: living_room_tv

alarm_control_panel:
  - platform: manual
    name: Home Alarm
    code: !secret alarm_code
    pending_time: 30 # The time in seconds before arming the alarm. Default is 60 seconds.
    trigger_time: 5 # The time in seconds before the alarm fires. Default is 120 seconds.

telegram_bot:
  - platform: polling
    api_key: !secret telegram_bot_api_key
    allowed_chat_ids:
      - !secret dereks_telegram_id
      - !secret kalees_telegram_id

ecobee:
  api_key: !secret ecobee_api_key

zwave:
  usb_path: /dev/ttyACM0
  device_config:
    light.kitchen_lights_level:
      refresh_value: true
      delay: 2

panel_iframe:
  mdiindex:
    title: MDI Icon Index
    icon: mdi:vector-square
    url: https://cdn.rawgit.com/james-fry/home-assistant-mdi/efd95d7a/home-assistant-mdi.html
  windy:
    title: 'Windy'
    icon: mdi:weather-windy
    url: !secret windy_url

android_ip_webcam:
  - host: 192.168.0.115
    name: Entrance
    username: !secret android_ip_webcam_user
    password: !secret android_ip_webcam_pass
    sensors:
      - battery_level
      - motion
      - light

media_player:
  - platform: cast
  - platform: firetv
    scan_interval: 2
  - platform: plex
  - platform: spotify
    client_id: !secret spotify_client_id
    client_secret: !secret spotify_client_secret

vacuum:
  - platform: xiaomi_miio
    host: 192.168.0.102
    token: !secret xiaomi_token

light:
  - platform: hue
    host: 192.168.0.100
    filename: phue.conf
    allow_hue_groups: true
  - platform: hue
    host: 192.168.0.118
    filename: phue2.conf
    allow_hue_groups: true
  - platform: hyperion
    host: 192.168.0.105
    port: 19444

camera:
  - platform: generic
    name: Weather Radar - Michigan
    still_image_url: !secret weather_radar_url
  - platform: mjpeg
    name: Living Room
    mjpeg_url: http://192.168.0.108/live

frontend:
  themes:
    dark_theme:
      # Main colors
      primary-color: '#5294E2'                                                        # Header
      accent-color: '#E45E65'                                                         # Accent color
      dark-primary-color: 'var(--accent-color)'                                       # Hyperlinks
      light-primary-color: 'var(--accent-color)'                                      # Horizontal line in about
      # Text colors
      primary-text-color: '#FFFFFF'                                                   # Primary text colour, here is referencing dark-primary-color
      text-primary-color: 'var(--primary-text-color)'                                 # Primary text colour
      secondary-text-color: '#5294E2'                                                 # For secondary titles in more info boxes etc.
      disabled-text-color: '#7F848E'                                                  # Disabled text colour
      label-badge-border-color: 'green'                                               # Label badge border, just a reference value
      # Background colors
      primary-background-color: '#383C45'                                             # Settings background
      secondary-background-color: '#383C45'                                           # Main card UI background
      divider-color: 'rgba(0, 0, 0, .12)'                                             # Divider
      # Table rows
      table-row-background-color: '#353840'                                           # Table row
      table-row-alternative-background-color: '#3E424B'                               # Table row alternative
      # Nav Menu
      paper-listbox-color: 'var(--primary-color)'                                     # Navigation menu selection hoover
      paper-listbox-background-color: '#2E333A'                                       # Navigation menu background
      paper-grey-50: 'var(--primary-text-color)'
      paper-grey-200: '#414A59'                                                       # Navigation menu selection
      # Paper card
      paper-card-header-color: 'var(--accent-color)'                                  # Card header text colour
      paper-card-background-color: '#434954'                                          # Card background colour
      paper-dialog-background-color: '#434954'                                        # Card dialog background colour
      paper-item-icon-color: 'var(--primary-text-color)'                              # Icon color
      paper-item-icon-active-color: '#F9C536'                                         # Icon color active
      paper-item-icon_-_color: 'green'
      paper-item-selected_-_background-color: '#434954'                               # Popup item select
      paper-tabs-selection-bar-color: 'green'
      # Labels
      label-badge-red: 'var(--accent-color)'                                          # References the brand colour label badge border
      label-badge-text-color: 'var(--primary-text-color)'                             # Now same as label badge border but that's a matter of taste
      label-badge-background-color: '#2E333A'                                         # Same, but can also be set to transparent here
      # Switches
      paper-toggle-button-checked-button-color: 'var(--accent-color)'
      paper-toggle-button-checked-bar-color: 'var(--accent-color)'
      paper-toggle-button-checked-ink-color: 'var(--accent-color)'
      paper-toggle-button-unchecked-button-color: 'var(--disabled-text-color)'
      paper-toggle-button-unchecked-bar-color: 'var(--disabled-text-color)'
      paper-toggle-button-unchecked-ink-color: 'var(--disabled-text-color)'
      # Sliders
      paper-slider-knob-color: 'var(--accent-color)'
      paper-slider-knob-start-color: 'var(--accent-color)'
      paper-slider-pin-color: 'var(--accent-color)'
      paper-slider-active-color: 'var(--accent-color)'
      paper-slider-container-color: 'linear-gradient(var(--primary-background-color), var(--secondary-background-color)) no-repeat'
      paper-slider-secondary-color: 'var(--secondary-background-color)'
      paper-slider-disabled-active-color: 'var(--disabled-text-color)'
      paper-slider-disabled-secondary-color: 'var(--disabled-text-color)'
      # Google colors
      google-red-500: '#E45E65'
      google-green-500: '#39E949'
