- alias: Turn off bedroom motion automatically
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: input_select.lighting_mode
      to: 'Lights Off'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: group.derek_kalee
        state: 'home'
      - condition: state
        entity_id: light.bedroom_lamps
        state: 'off'
      - condition: state
        entity_id: switch.office_pc
        state: 'off'
  action:
    - service: input_boolean.turn_off
      entity_id: input_boolean.bedroom_motion