- alias: Guest Mode - On Arrival
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: group.guests
      to: 'home'
    - platform: state
      entity_id: group.guests
      to: 'not_home'
  action:
    - service_template: >
        {% if trigger.state == 'home' %} input_boolean.turn_on
        {% elif trigger.state == 'not_home' %} input_boolean.turn_off
        {% endif %}
      entity_id: input_boolean.guest_mode

- alias: Guest Mode - On Start
  initial_state: 'on'
  trigger:
    - platform: homeassistant
      event: start
  condition:
    - condition: state
      entity_id: group.guests
      state: 'home'
  action:
    - service: homeassistant.turn_on
      entity_id: input_boolean.guest_mode
