- alias: Last Room With Motion - Livingroom
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: sensor.sn2_livingroom_bar_pir
      to: 'motion detected'
    - platform: state
      entity_id: sensor.sn5_livingroom_couch_pir
      to: 'motion detected'
  condition:
    - condition: template
      value_template: '{{ states.input_select.last_room_with_motion.state != "Living Room" }}'
  action:
    - service: input_select.select_option
      entity_id: input_select.last_room_with_motion
      data:
        option: 'Living Room'

- alias: Last Room With Motion - Kitchen
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: sensor.sn3_kitchen_pir
      to: 'motion detected'
  condition:
    - condition: template
      value_template: '{{ states.input_select.last_room_with_motion.state != "Kitchen" }}'
  action:
    - service: input_select.select_option
      entity_id: input_select.last_room_with_motion
      data:
        option: 'Kitchen'

- alias: Last Room With Motion - Laundry Room
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: binary_sensor.laundry_room_motion_sensor_sensor
      to: 'on'
  condition:
    - condition: template
      value_template: '{{ states.input_select.last_room_with_motion.state != "Laundry Room" }}'
  action:
    - service: input_select.select_option
      entity_id: input_select.last_room_with_motion
      data:
        option: 'Laundry Room'

- alias: Last Room With Motion - Master Bedroom
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: sensor.sn1_bedroom_pir
      to: 'motion detected'
  condition:
    - condition: template
      value_template: '{{ states.input_select.last_room_with_motion.state != "Master Bedroom" }}'
  action:
    - service: input_select.select_option
      entity_id: input_select.last_room_with_motion
      data:
        option: 'Master Bedroom'

- alias: Last Room With Motion - Master Bathroom
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: sensor.sn4_master_bathroom_pir
      to: 'motion detected'
  condition:
    - condition: template
      value_template: '{{ states.input_select.last_room_with_motion.state != "Master Bathroom" }}'
  action:
    - service: input_select.select_option
      entity_id: input_select.last_room_with_motion
      data:
        option: 'Master Bathroom'
