- alias: Lights Off - Derek and Kalee Left
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: group.derek_kalee
      to: 'not_home'
  condition:
    - condition: state
      entity_id: device_tracker.nolans_phone
      state: 'home'
  action:
    - service: scene.turn_on
      entity_id: scene.lights_off_dk
    - delay: '00:00:05'
    - service: scene.turn_on
      entity_id: scene.lights_off_dk

- alias: Lights Off - Nolan Left
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: device_tracker.nolans_phone
      to: 'not_home'
  condition:
    - condition: state
      entity_id: group.derek_kalee
      state: 'home'
  action:
    - service: light.turn_off
      entity_id: light.nolans_bedroom_lights

- alias: Lights Off - Everyone Left
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: group.people
      to: 'not_home'
  action:
    - service: scene.turn_on
      entity_id: scene.no_ones_home
    - delay: '00:00:05'
    - service: scene.turn_on
      entity_id: scene.no_ones_home
    - service: media_player.media_pause
      entity_id: media_player.amazon_fire_tv
