- alias: Turn server back on if turned off
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: switch.plex_server
      to: 'off'
  action:
    - service: switch.turn_on
      entity_id: switch.plex_server